services:
  kafka-tools:
    image: provectuslabs/kafka-ui:latest
    networks:
      - dev-service
    environment:
      SPRING_CONFIG_ADDITIONAL-LOCATION: /toolbox/application.yml
    ports:
      - "28080:8080"
    volumes:
      - ./kafka_ui/application.yml:/toolbox/application.yml
