services:
  minio_service:
    image: minio/minio:${MINIO_VERSION}
    restart: unless-stopped
    networks:
      - dev-service
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

networks:
  dev-service:

volumes:
  minio_data:
