version: "3.8"

services:
  postgres_database:
    image: postgres:${POSTGRES_VERSION}
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgsql_data:
