services:
  valkey:
    image: valkey/${VALKEY_VERSION}
    environment:
      # It is only recommended for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "6379:6379"
    volumes:
      - "valkey_data:/data"

volumes:
  valkey_data:
    driver: local
